package:
  name: poppy-creature
  # version automatically set in the build.sh and blt.bat

source:
  path: ../


build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  build:
    - python
    - setuptools
    - pypot >3.0

  run:
    - python
    - ipython
    - pypot >3.0

test:

  # Python imports
  imports:
    - poppy
    - poppy.creatures

about:
  home: https://github.com/poppy-project/poppy-creature
  summary: 'Abstract Poppy Creature Software Library'
  license: GNU GENERAL PUBLIC LICENSE Version 3
